require "test_helper"

class Urbit::ChannelTest < Minitest::Test
  def test_a_Channel_is_initialized_with_a_name
    c = Urbit::Api::Channel.new "Test Channel"
    refute_nil c.name
    assert_equal 'Test Channel', c.name
  end

  def test_an_initialized_channel_has_an_autogenerated_key
    c = Urbit::Api::Channel.new "Test Channel"
    refute_nil c.key
  end

  def test_the_autogenerated_key_is_16_chars_long
    c = Urbit::Api::Channel.new "Test Channel"
    assert_equal 16, c.key.size
  end
end
