require "test_helper"

class Urbit::ChannelTest < Minitest::Test
  def setup
    @p = Urbit::Api::Pier.new
    @c = Urbit::Api::Channel.new @p, "Test Channel"
  end

  def test_a_Channel_is_initialized_with_a_name
    refute_nil @c.name
    assert_equal 'Test Channel', @c.name
  end

  def test_an_initialized_channel_has_an_autogenerated_key
    refute_nil @c.key
  end

  def test_the_autogenerated_key_is_16_chars_long
    assert_equal 16, @c.key.size
  end

  def test_can_send_a_message_once_opened
    @p = Urbit::Api::Pier.new
    c = @p.open_channel "Test Channel"
    assert_equal "a", c.send_message("Opening Airlock")
  end
end
